// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTXXugCpLcfiki8-U4fr0EdEIshsT2-s',
    appId: '1:39740084138:web:12edecc65c760ae9ad65d3',
    messagingSenderId: '39740084138',
    projectId: 'fluterchatpro',
    authDomain: 'fluterchatpro.firebaseapp.com',
    storageBucket: 'fluterchatpro.appspot.com',
    measurementId: 'G-KT47MP1BWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4-ClelIudlpO31n1hahbxGoAEX6m1sg',
    appId: '1:39740084138:android:934313c290506243ad65d3',
    messagingSenderId: '39740084138',
    projectId: 'fluterchatpro',
    storageBucket: 'fluterchatpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JGbT8ZWxHsW-JiqoVS8XrCAnAhvHV3M',
    appId: '1:39740084138:ios:8bfa800709f92322ad65d3',
    messagingSenderId: '39740084138',
    projectId: 'fluterchatpro',
    storageBucket: 'fluterchatpro.appspot.com',
    iosBundleId: 'com.mobiledevchtsca.fluterchatpro',
  );
}
